# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RVC2MQTT add-on
version: "1.0.0"
slug: rvc2mqtt
description: RVC2MQTT add-on
url: "https://github.com/spbrogan/ha_addon_rvc2mqtt/tree/main/rvc2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/spbrogan/{arch}-addon-rvc2mqtt"
