# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RVC2MQTT add-on
version: "1.1.1"
slug: rvc2mqtt
description: RVC2MQTT add-on
url: "https://github.com/spbrogan/ha_addon_rvc2mqtt/tree/main/rvc2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
host_network: true
privileged: ["NET_ADMIN"]
image: "ghcr.io/spbrogan/{arch}-addon-rvc2mqtt"
services:
  - mqtt:want

options:
  interface_name: "can0"
  floorplan_file_path: "default_config.yaml"  
  mqtt: {}
  floorplan:
    - name: DC_LOAD_STATUS
      type: tank_warmer
      instance: 34
      instance_name: waste tank heater
    - name: DC_LOAD_STATUS
      type: tank_warmer
      instance: 35
      instance_name: fresh water tank heater

schema:
  interface_name: str?
  floorplan_file_path: str
  mqtt:
    host: str?
    port: port?
    ca: str?
    cert: str?
    key: str?
    username: str?
    password: password?
    client_id: str?
  floorplan:
    - dgn: str?
      name: str?
      instance: int?
      group: int?
      type: str?
      instance_name: str?
